- hosts: all
  vars:
    # Vcenter configuration.
    vcenter_hostname: ""
    vcenter_username: ""
    vcenter_password: ""
    vsphere_datacenter: ""
    vm_name: ""

    # OTC configuration.
    obs_imagebucket: ""
    
    # OpenTelekomCloud terraform provider configuration
    OTC:
      username: ""
      password: ""
      domain_name: ""
      tenant_name: ""
      endpoint: ""
    
    # OpenTelekomCloud Infra info
    security_group: ""
    subnet_network_id: ""
    fixed_ip_address: ""
    mac_address: ""
    kms_key_alias: ""
    keypair: ""
    flavor_id: ""
    az: ""


  tasks:
  - name: Create project path
    shell: /bin/mktemp -d migration.XXX
    register: project_path

  - name: Create OVF
    shell: | 
        /usr/bin/ovftool \
        --powerOffSource \
        'vi://{{ vcenter_username }}:{{ vcenter_password }}@{{vcenter_hostname}}:443/{{ vsphere_datacenter }}/{{ vm_name }}' \
        {{ project_path }}/images
    
  - name: Upload image files to OBS bucket
    shell:  |
        /usr/local/bin/obsutil sync \
        '{{ project_path }}/images/{{ vm_name }}' \
        'obs://{{ obs_imagebucket }}/{{ vm_name }}' \
        --include=*.vmdk

  - name: Clean the local path of images
    shell:  |
        /bin/rm -rf \
        '{{ project_path }}/images'
  
  - name: Clone terraform script to project path
    shell:  |
        cd '{{ project_path }}'; \
        git clone git@github.com:lushanlushan/auto-migration.git 

  - name: Single VM migration 
    terraform:
      project_path: '{{ project_path }}/auto-migration/terraform/0_single_vm'
      force_init: yes
      variables: {
        "{{OTC}}",
        "{{security_group}}",
        "{{subnet_network_id}}",
        "{{fixed_ip_address}}",
        "{{mac_address}}",
        "{{kms_key_alias}}",
        "{{keypair}}",
        "{{flavor_id}}",
        "{{az}}"
      }
      state: present

