- hosts: all
  vars:
    # Vcenter configuration.
    vcenter_hostname: ""
    vcenter_username: ""
    vcenter_password: ""
    Datacenter: ""
    vm_name: ""

    # OTC configuration.
    obs_imagebucket: ""

    # OpenTelekomCloud terraform provider configuration
    OTC:
      username: ""
      password: ""
      domain_name: ""
      tenant_name: ""
      endpoint: ""

  tasks:
  - name: Create project path
    shell: /bin/mktemp -d migration.XXX
    register: project_path

  - name: Create OVF
    shell: | 
        /usr/bin/ovftool \
        --powerOffSource \
        'vi://{{ vcenter_username }}:{{ vcenter_password }}@{{vcenter_hostname}}:443/{{Datacenter}}/{{ vm_name }}' \
        {{ project_path }}/images
  
  - name: Count the data disks
    find:
      paths: "{{ project_path }}/images"
      file_type: file
      patterns: ['*.vmdk']
    register: disk_num
    
  - name: Upload image files to OBS bucket
    shell:  |
        /usr/local/bin/obsutil sync \
        '{{ project_path }}/images/{{ vm_name }}' \
        'obs://{{ obs_imagebucket }}/{{ vm_name }}' \
        --include=*.vmdk

  - name: Clean the local path of images
    shell:  |
        /bin/rm -rf \
        '{{ project_path }}/images'
  
  - name: Copy terraform script to project path
    shell:  |
        cd '{{ project_path }}'; \
        git clone git@github.com:lushanlushan/auto-migration.git 

  - name: Create system disk image on OTC via Terraform
    terraform:
      project_path: '{{ project_path }}/auto-migration/terraform/0_sys_image'
      force_init: yes
      variables: "{{OTC}}"
      state: present

  # - name: Create data disk image on OTC via Terraform
  #   terraform:
  #     project_path: '{{ project_path }}/auto-migration/terraform/1_disk_image'
  #     force_init: yes
  #     variables: "{{OTC}}"
  #     state: present


  - name: Create the migrated ECS instance on OTC
    terraform:
      pproject_path: '{{ project_path }}/auto-migration/terraform/2_ecs_creation'
      force_init: yes
      variables: "{{OTC}}"
      state: present